spring.application.name=gateway
server.port=8888

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# SpringDoc
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.config-url=/v3/api-docs/swagger-config
springdoc.swagger-ui.disable-swagger-default-url=true

# Microservice docs
springdoc.swagger-ui.urls[0].name=test
springdoc.swagger-ui.urls[0].url=/aggregate/test/v3/api-docs