spring.application.name=gateway
server.port=8888
# Remove both of these:
# server.servlet.context-path=/api
# spring.webflux.base-path=/api

#spring.cloud.gateway.routes[0].id=test
#spring.cloud.gateway.routes[0].uri=http://localhost:8001
#spring.cloud.gateway.routes[0].predicates[0]=Path=/api/test/**
#spring.cloud.gateway.routes[0].filters[0]=RewritePath=/api/(?<segment>.*), /$\{segment}
eureka.client.service-url.defaultZone=http://localhost:8761/eureka