spring.application.name=ConfigServerApplication

server.port=9999
server.servlet.context-path=/config

spring.cloud.config.server.git.uri=https://github.com/rajeshponna/config-server.git
spring.cloud.config.server.git.clone-on-start=true